**Create tensor**

In [ ]:
import tensorflow as tf

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

**Valid reshaping**

In [ ]:
tf.print("before reshape:\n", matrix)
tf.print("reshape to 3x2:\n", tf.reshape(matrix, [3, 2]))
tf.print("flatten into an 1-dimensional tensor:\n", tf.reshape(matrix, [-1]))

before reshape:
 [[1 2 3]
 [4 5 6]]
reshape to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
flatten into an 1-dimensional tensor:
 [1 2 3 4 5 6]


**Invalid reshaping**

In [ ]:
tf.print("invalid reshape:\n", tf.reshape(matrix, [3, 3]))

InvalidArgumentError: ignored