**Create an 1-dimensional tensor**

In [1]:
import tensorflow as tf

rank1_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
tf.print("shape:", tf.shape(rank1_tensor))
tf.print("rank:", tf.rank(rank1_tensor))
tf.print("size:", tf.size(rank1_tensor))

shape: [8]
rank: 1
size: 8


**Create an 2-dimensional tensor**

In [2]:
rank2_tensor = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])
tf.print("shape:", tf.shape(rank2_tensor))
tf.print("rank:", tf.rank(rank2_tensor))
tf.print("size:", tf.size(rank2_tensor))

shape: [4 3]
rank: 2
size: 12


**1-dimensional tensor single element indexing**

In [3]:
# rank1_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
tf.print("first element:", rank1_tensor[0])
tf.print("third element:", rank1_tensor[2])
tf.print("last element:", rank1_tensor[-1])

first element: 1
third element: 3
last element: 8


**1-dimensional tensor slicing: TensorFlow approach**

In [4]:
tf.print("all elements:", tf.slice(rank1_tensor, begin=[0], size = [8]))
tf.print("elements 1 ~ 5:", tf.slice(rank1_tensor, begin=[0], size = [5]))
tf.print("elements 3 ~ 8:", tf.slice(rank1_tensor, begin=[2], size = [6]))
tf.print("last three elements:", tf.slice(rank1_tensor, begin=[5], size = [3]))
tf.print("odd elements:", tf.gather(rank1_tensor, indices=[0, 2, 4, 6]))
tf.print("elements in reverse order:", tf.reverse(rank1_tensor, axis=[0]))

all elements: [1 2 3 ... 6 7 8]
elements 1 ~ 5: [1 2 3 4 5]
elements 3 ~ 8: [3 4 5 6 7 8]
last three elements: [6 7 8]
odd elements: [1 3 5 7]
elements in reverse order: [8 7 6 ... 3 2 1]


**1-dimensional tensor slicing: Pythonic approach**

In [5]:
tf.print("all elements:", rank1_tensor[:])
tf.print("elements 1 ~ 5:", rank1_tensor[0:5])
tf.print("elements 3 ~ 8:", rank1_tensor[2:9])
tf.print("last three elements:", rank1_tensor[-3:])
tf.print("odd elements:", rank1_tensor[::2])
tf.print("elements in reverse order:", rank1_tensor[::-1])

all elements: [1 2 3 ... 6 7 8]
elements 1 ~ 5: [1 2 3 4 5]
elements 3 ~ 8: [3 4 5 6 7 8]
last three elements: [6 7 8]
odd elements: [1 3 5 7]
elements in reverse order: [8 7 6 ... 3 2 1]


**N-dimensional tensor single element indexing**

In [6]:
# rank2_tensor = tf.constant([[1, 2, 3],
#                             [4, 5, 6],
#                             [7, 8, 9],
#                             [10, 11, 12]])
tf.print("second element in first row:", rank2_tensor[0, 1])
tf.print("last element in thrid row:", rank2_tensor[2, -1])
tf.print("third element in second column:", rank2_tensor[2, 1])

second element in first row: 2
last element in thrid row: 9
third element in second column: 8


**N-dimensional tensor slicing**

In [8]:
tf.print("all elements:\n", rank2_tensor[:])
tf.print("elements in third row:", rank2_tensor[2, :])
tf.print("elements in first column:", rank2_tensor[:, 0])
tf.print("first two elements in second row:", rank2_tensor[1, :2])

all elements:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [10 11 12]]
elements in third row: [7 8 9]
elements in first column: [1 4 7 10]
first two elements in second row: [4 5]
