**Create tensor**

In [1]:
import tensorflow as tf

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])


# for matrix multiplication
a_3x2 = tf.constant([
                  [1, 2],
                  [3, 4],
                  [5, 6]])

b_2x3 = tf.constant([
                  [1, 2, 3],
                  [4, 5, 6]
                  ])

**Addition**

In [2]:
c = tf.add(a, b)
tf.print("a + b =", c)

a + b = [5 7 9]


**Subtraction**

In [3]:
c = tf.subtract(a, b)
tf.print("a - b =", c)

a - b = [-3 -3 -3]


**Multiplication**

In [4]:
c = tf.multiply(a, b)
tf.print("a * b =", c)


a * b = [4 10 18]


**Division**

In [5]:
c = tf.divide(a, b)
tf.print("a / b =", c)

a / b = [0.25 0.4 0.5]


**Matrix multiplication**

In [6]:
d = tf.matmul(a_3x2, b_2x3)
tf.print("[a] * [b] =", d)

[a] * [b] = [[9 12 15]
 [19 26 33]
 [29 40 51]]


**Transpose of matrix**

In [7]:
tf.print("before:", a_3x2)
a_2x3 = tf.transpose(a_3x2)
tf.print("before:", a_2x3)

before: [[1 2]
 [3 4]
 [5 6]]
before: [[1 3 5]
 [2 4 6]]


**Determinant of matrix**

In [8]:
square = tf.constant([
                  [1, 2, 3],
                  [0, 4, 5],
                  [0, 0, 6]
                  ], dtype=tf.float32)

det = tf.linalg.det(square)
tf.print("determinant: ", det)

determinant:  24
