**Install and import cirq**

In [1]:
# !pip install --upgrade
!pip install cirq
import cirq
import numpy as np

In [2]:
# single qubit gate
print(cirq.H)
print(np.real(cirq.unitary(cirq.H)))

# two-qubit gate
print(cirq.CNOT)
print(np.real(cirq.unitary(cirq.CNOT)))

print(cirq.MeasurementGate)

H
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
CNOT
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
<class 'cirq.ops.measurement_gate.MeasurementGate'>


**Gate to operation**

In [3]:
# gate
print(cirq.H, type(cirq.H).__name__)

# operation
qubit = cirq.NamedQubit('qubit1')
hadamard_operation = cirq.H(qubit)
print(hadamard_operation, type(hadamard_operation).__name__)

H HPowGate
H(qubit1) GateOperation
